### PR TITLE
V0.6.0

### PR DESCRIPTION
**Pull request by sdc50**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sdc50** [comment]
@swainn It looks like the build is failing because it can't resolve the environment due to `django-ranged-response` being pinned to `- django >=1.8.0,<4`. Can you update that package? 

https://github.com/conda-forge/django-ranged-response-feedstock

**Comment by swainn** [comment]
> @swainn It looks like the build is failing because it can't resolve the environment due to `django-ranged-response` being pinned to `- django >=1.8.0,<4`. Can you update that package?
> 
> https://github.com/conda-forge/django-ranged-response-feedstock

I just merged your pr on the `django-ranged-response`. I'll re-run the checks.

**Review by swainn — APPROVED** [review]

**Comment by sdc50** [comment]
@conda-forge-admin, please restart ci

**Comment by sdc50** [comment]
@swainn This is ready to merge now.

**Pull request merged**
